name: Foundry CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FOUNDRY_PROFILE: ci
  FOUNDRY_SOLC_VERSION: 0.8.20

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      # Add caching to speed up workflow
      - name: Cache Forge dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/forge
            ~/.cache/foundry
            lib/
            out/
            cache/
          key: ${{ runner.os }}-forge-${{ hashFiles('**/foundry.toml', '**/remappings.txt', '**/forge-cache/**') }}
          restore-keys: |
            ${{ runner.os }}-forge-

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install --no-commit

      - name: Show Forge config
        run: |
          forge --version
          forge config --list
          forge remappings
          
      - name: Check code formatting
        run: |
          # Check formatting but don't fail the workflow
          forge fmt --check || echo "Formatting issues detected, but continuing workflow"

      - name: Build contracts
        run: forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          # Run tests with more verbose output and lower optimizer runs for CI
          forge test -vvv --optimize --optimizer-runs 1000
        id: test

      - name: Run Coverage Report
        if: success()
        run: |
          forge coverage --report summary
        id: coverage
